# Generated by Django 5.0.4 on 2024-06-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Moscow", "Moscow"),
                    ("Saint Petersburg", "Saint Petersburg"),
                    ("Novosibirsk", "Novosibirsk"),
                    ("Kazan", "Kazan"),
                    ("Krasnoyarsk", "Krasnoyarsk"),
                    ("Yekaterinburg", "Yekaterinburg"),
                    ("Omsk", "Omsk"),
                    ("Tomsk", "Tomsk"),
                ],
                max_length=50,
                null=True,
                verbose_name="city",
            ),
        ),
    ]
