# Generated by Django 5.0.4 on 2024-05-23 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_blog"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="views_count",
            field=models.IntegerField(default=0, verbose_name="просмотры"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="slug",
            field=models.CharField(
                help_text="человекопонятный URL",
                max_length=150,
                verbose_name="Наименование",
            ),
        ),
    ]
