# Generated by Django 5.0.4 on 2024-05-23 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_blog_views_count_alter_blog_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="slug",
            field=models.CharField(
                blank=True,
                help_text="человекопонятный URL",
                max_length=150,
                null=True,
                verbose_name="Наименование",
            ),
        ),
    ]
