# Generated by Django 5.0.4 on 2024-05-23 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_blog_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="views_count",
            field=models.CharField(default=0, verbose_name="просмотры"),
        ),
    ]
