# Generated by Django 5.0.4 on 2024-05-23 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_blog_views_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="views_count",
            field=models.IntegerField(default=0, verbose_name="просмотры"),
        ),
    ]
