# Generated by Django 5.0.4 on 2024-06-07 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_blog_views_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namber_version', models.IntegerField(help_text='введите версию товара', verbose_name='Версия')),
                ('name_version', models.CharField(help_text='введите название версии', max_length=150, verbose_name='Имя версии')),
                ('is_activ_version', models.BooleanField(help_text='укажите актуальность версии', verbose_name='Актуальная')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Версия',
                'verbose_name_plural': 'Версии',
            },
        ),
    ]
