# Generated by Django 5.0.4 on 2024-06-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_category_owner_product_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name', 'price', 'data_create', 'data_update', 'category', 'description'], 'permissions': (('can_unpublish_product', 'Can unpublish product'), ('change_product_description', 'Can change product description'), ('change_product_category', 'Can change product category')), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
